# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vec_prod <- function(x, y) {
    .Call('_pemultinom_vec_prod', PACKAGE = 'pemultinom', x, y)
}

vec_diff <- function(x, y) {
    .Call('_pemultinom_vec_diff', PACKAGE = 'pemultinom', x, y)
}

mx_vec_prod_i <- function(x, y, i) {
    .Call('_pemultinom_mx_vec_prod_i', PACKAGE = 'pemultinom', x, y, i)
}

mx_prod <- function(x, y) {
    .Call('_pemultinom_mx_prod', PACKAGE = 'pemultinom', x, y)
}

xb_mx_plus <- function(xb, beta0) {
    .Call('_pemultinom_xb_mx_plus', PACKAGE = 'pemultinom', xb, beta0)
}

vec_sum <- function(x) {
    .Call('_pemultinom_vec_sum', PACKAGE = 'pemultinom', x)
}

max2 <- function(x, y) {
    .Call('_pemultinom_max2', PACKAGE = 'pemultinom', x, y)
}

vec_max <- function(x) {
    .Call('_pemultinom_vec_max', PACKAGE = 'pemultinom', x)
}

vec_devide_number <- function(x, y) {
    .Call('_pemultinom_vec_devide_number', PACKAGE = 'pemultinom', x, y)
}

vec_multiply_number <- function(x, y) {
    .Call('_pemultinom_vec_multiply_number', PACKAGE = 'pemultinom', x, y)
}

vec_square <- function(x) {
    .Call('_pemultinom_vec_square', PACKAGE = 'pemultinom', x)
}

vec_pointwise_prod <- function(x, y) {
    .Call('_pemultinom_vec_pointwise_prod', PACKAGE = 'pemultinom', x, y)
}

pr <- function(xb) {
    .Call('_pemultinom_pr', PACKAGE = 'pemultinom', xb)
}

xb_calc <- function(x, beta, beta0) {
    .Call('_pemultinom_xb_calc', PACKAGE = 'pemultinom', x, beta, beta0)
}

abs_value <- function(x) {
    .Call('_pemultinom_abs_value', PACKAGE = 'pemultinom', x)
}

vec_max_norm <- function(x) {
    .Call('_pemultinom_vec_max_norm', PACKAGE = 'pemultinom', x)
}

test <- function(x) {
    .Call('_pemultinom_test', PACKAGE = 'pemultinom', x)
}

soft_thresholding <- function(z, gamma) {
    .Call('_pemultinom_soft_thresholding', PACKAGE = 'pemultinom', z, gamma)
}

pemultinom_c <- function(x, y, lambda_list, max_iter, tol) {
    .Call('_pemultinom_pemultinom_c', PACKAGE = 'pemultinom', x, y, lambda_list, max_iter, tol)
}

penalized_quad <- function(A, b, lambda_list, max_iter, tol) {
    .Call('_pemultinom_penalized_quad', PACKAGE = 'pemultinom', A, b, lambda_list, max_iter, tol)
}

pemultinom_c_reverse <- function(x, y, lambda_list, max_iter, tol, zero_ind, weights) {
    .Call('_pemultinom_pemultinom_c_reverse', PACKAGE = 'pemultinom', x, y, lambda_list, max_iter, tol, zero_ind, weights)
}

